name: Build KubeTaint  

on:
  push:
    branches: [ slikube-enhancement, master ]
  pull_request:
     branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    # - name: Install Conda
    #   uses: conda-incubator/setup-miniconda@v2
        
    - name: Install Python Dependencies
      run: | 
        # conda env create -f environment.yml
        # conda activate slikube-enhancement        
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install requests
        pip install pandas
        pip install PyYAML
        pip install ruamel.yaml
        pip install pathlib
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run integration and taint-related tests 
      run: |
        python TEST_PARSING.py  